apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: whatwant-rb

subjects:
- kind: ServiceAccount
  name: whatwant   
  apiGroup: ""

roleRef:
  kind: Role
  name: whatwant-role
  apiGroup: rbac.authorization.k8s.io
