apiVersion: v1
kind: Pod
metadata:
  name: git-sync

spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    args:
    - sleep
    - "370000"

    volumeMounts:
    - name: myrepo
      mountPath: "/repo"

  - name: git-sync
    image: k8s.gcr.io/git-sync/git-sync:v3.6.1
    args:
    - -ssh
    - -repo=git@github.com:whatwant-school/private-repo.git
    - -root=/repo
    - -dest=private-repo
    - -branch=main
    - -depth=1

    volumeMounts:
    - name: myrepo
      mountPath: "/repo"

    - name: git-secret
      mountPath: /etc/git-secret
      readOnly: true

    securityContext:
      runAsUser: 65533

  securityContext:
    fsGroup: 65533

  restartPolicy: Never

  volumes:
  - name: myrepo
    emptyDir: {}

  - name: git-secret
    secret:
      secretName: my-ssh
      defaultMode: 0400
