apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: rs-nfs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ubuntu

  template:
    metadata:
      labels:
        app: ubuntu

    spec:
      containers:
      - image: ubuntu:20.04
        name: worker1
        command: ["/bin/sleep", "3650d"]

        volumeMounts:
        - name: nfs-demo
          mountPath: /data/nfs

      volumes:
      - name: nfs-demo
        nfs:
          path: /srv/nfs
          server: 192.168.100.250
