apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: rs-web-v2

spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web-v2

  template:
    metadata:
      labels:
        app: node-web-v2

    spec:
      containers:
      - name: node-web
        image: whatwant/node-web:2.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
