apiVersion: apps/v1
kind: Deployment

metadata:
  name: dp-web  

spec:
  replicas: 3

  selector:
    matchLabels:
      app: node-web

  template:
    metadata:
      name: node-web
      labels:
        app: node-web

    spec:
      containers:
      - image: whatwant/node-web:2.0
        name: node-web
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
