apiVersion: batch/v1
kind: Job

metadata:
  name: job-throw-dice

spec:
  completions: 3
  parallelism: 3
  backoffLimit: 25

  template:
    spec:
      containers:
        - name: throw-dice
          image: kodekloud/throw-dice

      restartPolicy: Never
