apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-static

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu

  template:
    metadata:
      labels:
        app: ubuntu

    spec:
      containers:
      - image: ubuntu:20.04
        name: ubuntu
        command: ["/bin/sleep", "3650d"]

        volumeMounts:
        - name: pvc-static
          mountPath: /data/pv

      volumes:
        - name: pvc-static
          persistentVolumeClaim:
            claimName: pvc-50mi
